name: Release

on: [pull_request_review_comment]

jobs:
  approved:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: git rev-parse --abbrev-ref HEAD

  approved1:
    runs-on: ubuntu-20.04
    steps:
      - run: echo ${{ github.event.pull_request.head.ref }}
