name: Release

on: [pull_request_review_comment]

jobs:
  approved:
    if: startsWith(github.ref, 'refs/heads/rel.')
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Works!"

  approved1:
    runs-on: ubuntu-20.04
    steps:
      - run: echo ${{ github.event.pull_request }}
